 /*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package kompormoto.View;


import java.awt.Color;
import java.awt.Font;
import java.util.List;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JTable;
import javax.swing.JTextField;
import kompormoto.Controller.Controller_Kendaraann;
import kompormoto.DAO.DAO_Kendaraann;
import kompormoto.DAOImplement.Implement_Kendaraann;
import kompormoto.Model.Model_Kendaraann;
import kompormoto.TabelModel.Tabel_Model_Kendaraann;

/**
 *
 * @author ASUS
 */
public class View_Kendaraann extends javax.swing.JPanel {
    Controller_Kendaraann controller_kendaraann;
    Implement_Kendaraann implemet_kendaraann;
    
    /**
     * Creates new form View_Kendaraan
     */
    public View_Kendaraann() {
        initComponents();
        controller_kendaraann = new Controller_Kendaraann(this);
        implemet_kendaraann = new DAO_Kendaraann();
        controller_kendaraann.isiTable();
        
        btbatal.setVisible(false);
        bthapus.setVisible(false);
        bttampil.setVisible(false);
        
        tbdata.getTableHeader().setFont(new Font("Segoe UI", Font.BOLD, 12));
        tbdata.getTableHeader().setOpaque(false);
        tbdata.getTableHeader().setBackground(new Color(6,114,202));
        tbdata.getTableHeader().setForeground(new Color(0, 0, 0));
        tbdata.setRowHeight(25);
        
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnmain = new javax.swing.JPanel();
        pndatatransaksikend = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbdata = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        bttambah = new javax.swing.JButton();
        btbatal = new javax.swing.JButton();
        bthapus = new javax.swing.JButton();
        txtcari = new javax.swing.JTextField();
        btcari = new javax.swing.JButton();
        bttampil = new javax.swing.JButton();
        updatetransaksikend = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        bttambah1 = new javax.swing.JButton();
        btbatal1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtkode = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txttotal = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtnama = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        cbjenis = new javax.swing.JComboBox<>();
        txtharga = new javax.swing.JTextField();
        txtmerk = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtpajak = new javax.swing.JTextField();
        txttelepon = new javax.swing.JTextField();
        txtalamat = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        tambahtransaksikend = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        btbatal2 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        txtkode1 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        txttotal1 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        txtnama1 = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        cbjenis1 = new javax.swing.JComboBox<>();
        txtharga1 = new javax.swing.JTextField();
        txtmerk1 = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        txtpajak1 = new javax.swing.JTextField();
        txtnalamat1 = new javax.swing.JTextField();
        txttelepon1 = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        bttambah2 = new javax.swing.JButton();
        tampiltransaksikend = new javax.swing.JPanel();
        jLabel32 = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        btbatal4 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel36 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JSeparator();
        lbalamat = new javax.swing.JLabel();
        lbnama = new javax.swing.JLabel();
        lbnotelp = new javax.swing.JLabel();
        btprint = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel39 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        lbjenis = new javax.swing.JLabel();
        lbtotal = new javax.swing.JLabel();
        lbpajak = new javax.swing.JLabel();
        lbharga = new javax.swing.JLabel();
        lbmerk = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        lbkode = new javax.swing.JLabel();
        btedit5 = new javax.swing.JButton();

        setLayout(new java.awt.CardLayout());

        pnmain.setBackground(new java.awt.Color(255, 255, 255));
        pnmain.setLayout(new java.awt.CardLayout());

        pndatatransaksikend.setBackground(new java.awt.Color(255, 255, 255));

        tbdata.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbdata.setFocusable(false);
        tbdata.setIntercellSpacing(new java.awt.Dimension(0, 0));
        tbdata.setRowHeight(20);
        tbdata.setSelectionBackground(new java.awt.Color(6, 114, 202));
        tbdata.setShowGrid(false);
        tbdata.getTableHeader().setReorderingAllowed(false);
        tbdata.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbdataMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbdata);

        jLabel1.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 30)); // NOI18N
        jLabel1.setText("Data Transaksi Kendaraan");

        bttambah.setBackground(new java.awt.Color(255, 255, 255));
        bttambah.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        bttambah.setIcon(new javax.swing.ImageIcon("E:\\Kuliah\\smt 4\\Prak PBO\\ProjectAkhir1\\KomporMoto\\img\\file_20px.png")); // NOI18N
        bttambah.setText("Tambah");
        bttambah.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(6, 114, 202), 1, true));
        bttambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttambahActionPerformed(evt);
            }
        });

        btbatal.setBackground(new java.awt.Color(255, 255, 255));
        btbatal.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btbatal.setIcon(new javax.swing.ImageIcon("E:\\Kuliah\\smt 4\\Prak PBO\\ProjectAkhir1\\KomporMoto\\img\\unavailable_20px.png")); // NOI18N
        btbatal.setText("Batal");
        btbatal.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(6, 114, 202), 1, true));
        btbatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btbatalActionPerformed(evt);
            }
        });

        bthapus.setBackground(new java.awt.Color(255, 255, 255));
        bthapus.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        bthapus.setIcon(new javax.swing.ImageIcon("E:\\Kuliah\\smt 4\\Prak PBO\\ProjectAkhir1\\KomporMoto\\img\\Delete_20px.png")); // NOI18N
        bthapus.setText("Hapus");
        bthapus.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(6, 114, 202), 1, true));
        bthapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bthapusActionPerformed(evt);
            }
        });

        txtcari.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(6, 114, 202), 2));
        txtcari.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtcariMouseClicked(evt);
            }
        });
        txtcari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtcariKeyTyped(evt);
            }
        });

        btcari.setBackground(new java.awt.Color(255, 255, 255));
        btcari.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btcari.setIcon(new javax.swing.ImageIcon("E:\\Kuliah\\smt 4\\Prak PBO\\ProjectAkhir1\\KomporMoto\\img\\searcch_24px.png")); // NOI18N
        btcari.setText("Cari");
        btcari.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(6, 114, 202)));
        btcari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btcariActionPerformed(evt);
            }
        });

        bttampil.setBackground(new java.awt.Color(255, 255, 255));
        bttampil.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bttampil.setIcon(new javax.swing.ImageIcon("E:\\Kuliah\\smt 4\\Prak PBO\\ProjectAkhir1\\KomporMoto\\img\\show_property_30px.png")); // NOI18N
        bttampil.setText("Tampil");
        bttampil.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(6, 114, 202), 2));
        bttampil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttampilActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pndatatransaksikendLayout = new javax.swing.GroupLayout(pndatatransaksikend);
        pndatatransaksikend.setLayout(pndatatransaksikendLayout);
        pndatatransaksikendLayout.setHorizontalGroup(
            pndatatransaksikendLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pndatatransaksikendLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pndatatransaksikendLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pndatatransaksikendLayout.createSequentialGroup()
                        .addGroup(pndatatransaksikendLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addGroup(pndatatransaksikendLayout.createSequentialGroup()
                                .addGroup(pndatatransaksikendLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 654, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(pndatatransaksikendLayout.createSequentialGroup()
                        .addComponent(bttambah, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(bthapus, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btbatal, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtcari, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btcari, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19))))
            .addGroup(pndatatransaksikendLayout.createSequentialGroup()
                .addGap(383, 383, 383)
                .addComponent(bttampil, javax.swing.GroupLayout.PREFERRED_SIZE, 366, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 496, Short.MAX_VALUE))
        );
        pndatatransaksikendLayout.setVerticalGroup(
            pndatatransaksikendLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pndatatransaksikendLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(pndatatransaksikendLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pndatatransaksikendLayout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addGroup(pndatatransaksikendLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtcari, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btcari)))
                    .addGroup(pndatatransaksikendLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pndatatransaksikendLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btbatal, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bthapus, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bttambah, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(28, 28, 28)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(bttampil, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1875, 1875, 1875))
        );

        pnmain.add(pndatatransaksikend, "card2");

        updatetransaksikend.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 30)); // NOI18N
        jLabel2.setText("Edit Data Transaksi Kendaraan");

        bttambah1.setBackground(new java.awt.Color(255, 255, 255));
        bttambah1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        bttambah1.setIcon(new javax.swing.ImageIcon("E:\\Kuliah\\smt 4\\Prak PBO\\ProjectAkhir1\\KomporMoto\\img\\edit_row_24px.png")); // NOI18N
        bttambah1.setText("Edit");
        bttambah1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(6, 114, 202), 1, true));
        bttambah1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttambah1ActionPerformed(evt);
            }
        });

        btbatal1.setBackground(new java.awt.Color(255, 255, 255));
        btbatal1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btbatal1.setIcon(new javax.swing.ImageIcon("E:\\Kuliah\\smt 4\\Prak PBO\\ProjectAkhir1\\KomporMoto\\img\\cancel_214px.png")); // NOI18N
        btbatal1.setText("Batal");
        btbatal1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(6, 114, 202), 1, true));
        btbatal1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btbatal1ActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        jLabel3.setText("Kode Transaksi");

        txtkode.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(6, 114, 202), 2, true));
        txtkode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtkodeActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        jLabel6.setText("Harga Kendaraan");

        jLabel7.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        jLabel7.setText("Merk Kendaraan");

        txttotal.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(6, 114, 202), 2, true));

        jLabel8.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        jLabel8.setText("Nama Pembeli");

        txtnama.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(6, 114, 202), 2, true));

        jLabel9.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        jLabel9.setText("Jenis Kendaraan");

        cbjenis.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Silahkan Pilih--", "Beat", "Vario 125", "Vario 150", "PCX", "CBR 150R", "CBR 250RR", "CB 150R", "R15", "R25", "AEROX 155", "LEXi 125", "Mio M3 125", "NMAX 155", "Vixion 155", " ", " ", " ", " ", " " }));
        cbjenis.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(6, 114, 202), 2, true));
        cbjenis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbjenisActionPerformed(evt);
            }
        });

        txtharga.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(6, 114, 202), 2, true));

        txtmerk.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(6, 114, 202), 2, true));

        jLabel10.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        jLabel10.setText("Pajak");

        jLabel11.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        jLabel11.setText("Total");

        txtpajak.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(6, 114, 202), 2, true));

        txttelepon.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(6, 114, 202), 2, true));

        txtalamat.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(6, 114, 202), 2, true));

        jLabel23.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        jLabel23.setText("No Telepon");

        jLabel24.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        jLabel24.setText("Alamat");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel8)
                    .addComponent(jLabel23)
                    .addComponent(jLabel6)
                    .addComponent(jLabel24)
                    .addComponent(jLabel9)
                    .addComponent(jLabel7)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11))
                .addGap(78, 78, 78)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtmerk, javax.swing.GroupLayout.PREFERRED_SIZE, 812, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(txtpajak, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtharga, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(cbjenis, javax.swing.GroupLayout.Alignment.LEADING, 0, 812, Short.MAX_VALUE)
                        .addComponent(txtalamat, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txttelepon, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtnama, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtkode, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txttotal)))
                .addContainerGap(225, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtkode, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(43, 43, 43)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtnama, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addGap(49, 49, 49)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txttelepon, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel23))
                        .addGap(52, 52, 52)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtalamat, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel24))
                        .addGap(48, 48, 48)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(cbjenis, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addGap(51, 51, 51)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtmerk, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addGap(50, 50, 50)
                        .addComponent(txtharga, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel6))
                .addGap(44, 44, 44)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtpajak, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addGap(48, 48, 48)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txttotal, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addContainerGap(354, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout updatetransaksikendLayout = new javax.swing.GroupLayout(updatetransaksikend);
        updatetransaksikend.setLayout(updatetransaksikendLayout);
        updatetransaksikendLayout.setHorizontalGroup(
            updatetransaksikendLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(updatetransaksikendLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(updatetransaksikendLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(updatetransaksikendLayout.createSequentialGroup()
                        .addGroup(updatetransaksikendLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 654, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(updatetransaksikendLayout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(bttambah1, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btbatal1, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(581, Short.MAX_VALUE))))
        );
        updatetransaksikendLayout.setVerticalGroup(
            updatetransaksikendLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, updatetransaksikendLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(updatetransaksikendLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bttambah1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btbatal1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(1118, Short.MAX_VALUE))
        );

        pnmain.add(updatetransaksikend, "card2");

        tambahtransaksikend.setBackground(new java.awt.Color(255, 255, 255));

        jLabel12.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 30)); // NOI18N
        jLabel12.setText("Tambah Data Transaksi Kendaraan");

        btbatal2.setBackground(new java.awt.Color(255, 255, 255));
        btbatal2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btbatal2.setIcon(new javax.swing.ImageIcon("E:\\Kuliah\\smt 4\\Prak PBO\\ProjectAkhir1\\KomporMoto\\img\\cancel_201px.png")); // NOI18N
        btbatal2.setText("Batal");
        btbatal2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(6, 114, 202), 1, true));
        btbatal2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btbatal2ActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel13.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        jLabel13.setText("Kode Transaksi");

        txtkode1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(6, 114, 202), 2));
        txtkode1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtkode1ActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        jLabel15.setText("Harga Kendaraan");

        jLabel16.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        jLabel16.setText("Merk Kendaraan");

        txttotal1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(6, 114, 202), 2));

        jLabel17.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        jLabel17.setText("Nama Pembeli");

        txtnama1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(6, 114, 202), 2));

        jLabel18.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        jLabel18.setText("Jenis Kendaraan");

        cbjenis1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Silahkan Pilih--", "Beat", "Vario 125", "Vario 150", "PCX", "CBR 150R", "CBR 250RR", "CB 150R", "R15", "R25", "AEROX 155", "LEXi 125", "Mio M3 125", "NMAX 155", "Vixion 155", " ", " ", " ", " ", " " }));
        cbjenis1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(6, 114, 202), 2));
        cbjenis1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbjenis1ActionPerformed(evt);
            }
        });

        txtharga1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(6, 114, 202), 2));

        txtmerk1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(6, 114, 202), 2));

        jLabel19.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        jLabel19.setText("Pajak");

        jLabel20.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        jLabel20.setText("Total");

        txtpajak1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(6, 114, 202), 2));

        txtnalamat1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(6, 114, 202), 2));

        txttelepon1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(6, 114, 202), 2));

        jLabel21.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        jLabel21.setText("No Telepon");

        jLabel22.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        jLabel22.setText("Alamat");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addComponent(jLabel17)
                    .addComponent(jLabel18)
                    .addComponent(jLabel16)
                    .addComponent(jLabel21)
                    .addComponent(jLabel22)
                    .addComponent(jLabel15)
                    .addComponent(jLabel19)
                    .addComponent(jLabel20))
                .addGap(97, 97, 97)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtnama1, javax.swing.GroupLayout.PREFERRED_SIZE, 665, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtkode1, javax.swing.GroupLayout.PREFERRED_SIZE, 665, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txttelepon1, javax.swing.GroupLayout.PREFERRED_SIZE, 665, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtnalamat1, javax.swing.GroupLayout.PREFERRED_SIZE, 665, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbjenis1, javax.swing.GroupLayout.PREFERRED_SIZE, 665, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtmerk1, javax.swing.GroupLayout.PREFERRED_SIZE, 665, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtharga1, javax.swing.GroupLayout.PREFERRED_SIZE, 665, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtpajak1, javax.swing.GroupLayout.PREFERRED_SIZE, 665, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txttotal1, javax.swing.GroupLayout.PREFERRED_SIZE, 665, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(343, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtkode1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addGap(34, 34, 34)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(txtnama1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txttelepon1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21))
                .addGap(37, 37, 37)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtnalamat1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22))
                .addGap(37, 37, 37)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cbjenis1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18))
                .addGap(43, 43, 43)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtmerk1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16))
                .addGap(47, 47, 47)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtharga1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15))
                .addGap(48, 48, 48)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtpajak1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19))
                .addGap(42, 42, 42)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txttotal1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20))
                .addContainerGap(350, Short.MAX_VALUE))
        );

        bttambah2.setBackground(new java.awt.Color(255, 255, 255));
        bttambah2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        bttambah2.setIcon(new javax.swing.ImageIcon("E:\\Kuliah\\smt 4\\Prak PBO\\ProjectAkhir1\\KomporMoto\\img\\file_20px.png")); // NOI18N
        bttambah2.setText("Tambah");
        bttambah2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(6, 114, 202), 1, true));
        bttambah2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttambah2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout tambahtransaksikendLayout = new javax.swing.GroupLayout(tambahtransaksikend);
        tambahtransaksikend.setLayout(tambahtransaksikendLayout);
        tambahtransaksikendLayout.setHorizontalGroup(
            tambahtransaksikendLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tambahtransaksikendLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tambahtransaksikendLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(tambahtransaksikendLayout.createSequentialGroup()
                        .addGroup(tambahtransaksikendLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 654, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(tambahtransaksikendLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(bttambah2, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btbatal2, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        tambahtransaksikendLayout.setVerticalGroup(
            tambahtransaksikendLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tambahtransaksikendLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(tambahtransaksikendLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btbatal2, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(bttambah2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnmain.add(tambahtransaksikend, "card2");

        tampiltransaksikend.setBackground(new java.awt.Color(255, 255, 255));

        jLabel32.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 30)); // NOI18N
        jLabel32.setText("Transaksi Kendaraan");

        btbatal4.setBackground(new java.awt.Color(255, 255, 255));
        btbatal4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btbatal4.setIcon(new javax.swing.ImageIcon("E:\\Kuliah\\smt 4\\Prak PBO\\ProjectAkhir1\\KomporMoto\\img\\cancel_24px11.png")); // NOI18N
        btbatal4.setText("Batal");
        btbatal4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(6, 114, 202), 1, true));
        btbatal4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btbatal4ActionPerformed(evt);
            }
        });

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jLabel36.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        jLabel36.setText("Nama Pembeli  :");

        jLabel40.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        jLabel40.setText("No Telepon  :");

        jLabel41.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        jLabel41.setText("Alamat  :");

        jLabel5.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        jLabel5.setText("Biodata Pembeli");

        lbalamat.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N

        lbnama.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N

        lbnotelp.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(222, 222, 222)
                        .addComponent(jLabel5))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(188, 188, 188)
                        .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(95, 95, 95)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel41)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lbalamat, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel36)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 117, Short.MAX_VALUE)
                                .addComponent(lbnama, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel40)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lbnotelp, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(10, 10, 10)))
                .addGap(47, 47, 47))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(49, 49, 49)
                        .addComponent(jLabel36))
                    .addComponent(lbnama, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(73, 73, 73)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel40)
                    .addComponent(lbnotelp, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(71, 71, 71)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbalamat, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel41))
                .addContainerGap(210, Short.MAX_VALUE))
        );

        btprint.setBackground(new java.awt.Color(255, 255, 255));
        btprint.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btprint.setIcon(new javax.swing.ImageIcon("E:\\Kuliah\\smt 4\\Prak PBO\\ProjectAkhir1\\KomporMoto\\img\\print_24px.png")); // NOI18N
        btprint.setText("Print");
        btprint.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(6, 114, 202), 1, true));
        btprint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btprintActionPerformed(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jLabel39.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        jLabel39.setText("Total");

        jLabel38.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        jLabel38.setText("Pajak  :");

        jLabel34.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        jLabel34.setText("Harga Kendaraan  :");

        jLabel35.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        jLabel35.setText("Merk Kendaraan  :");

        jLabel37.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        jLabel37.setText("Jenis Kendaraan  :");

        jLabel4.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        jLabel4.setText("Kendaraan Terjual");

        lbjenis.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N

        lbtotal.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N

        lbpajak.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N

        lbharga.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N

        lbmerk.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel39)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel34)
                                    .addComponent(jLabel38))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lbtotal, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbpajak, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbharga, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel35)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lbmerk, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel37)
                                .addGap(130, 130, 130)
                                .addComponent(lbjenis, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(19, 19, 19)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(193, 193, 193)
                        .addComponent(jLabel4))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(167, 167, 167)
                        .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel37)
                    .addComponent(lbjenis, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(53, 53, 53)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel35, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbmerk, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(55, 55, 55)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel34, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbharga, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(51, 51, 51)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel38, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbpajak, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(56, 56, 56)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel39, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbtotal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel14.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        jLabel14.setText("Kode Transaksi  :");

        lbkode.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N

        btedit5.setBackground(new java.awt.Color(255, 255, 255));
        btedit5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btedit5.setIcon(new javax.swing.ImageIcon("E:\\Kuliah\\smt 4\\Prak PBO\\ProjectAkhir1\\KomporMoto\\img\\edit_row_24px.png")); // NOI18N
        btedit5.setText("Edit");
        btedit5.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(6, 114, 202), 1, true));
        btedit5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btedit5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout tampiltransaksikendLayout = new javax.swing.GroupLayout(tampiltransaksikend);
        tampiltransaksikend.setLayout(tampiltransaksikendLayout);
        tampiltransaksikendLayout.setHorizontalGroup(
            tampiltransaksikendLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tampiltransaksikendLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tampiltransaksikendLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel32)
                    .addGroup(tampiltransaksikendLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(btprint, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btedit5, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btbatal4, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 654, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(tampiltransaksikendLayout.createSequentialGroup()
                        .addGroup(tampiltransaksikendLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(tampiltransaksikendLayout.createSequentialGroup()
                                .addGap(424, 424, 424)
                                .addComponent(jLabel14)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(tampiltransaksikendLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(tampiltransaksikendLayout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addComponent(lbkode, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(86, Short.MAX_VALUE))
        );
        tampiltransaksikendLayout.setVerticalGroup(
            tampiltransaksikendLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tampiltransaksikendLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel32)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(tampiltransaksikendLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tampiltransaksikendLayout.createSequentialGroup()
                        .addGroup(tampiltransaksikendLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btbatal4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btedit5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(48, 48, 48))
                    .addGroup(tampiltransaksikendLayout.createSequentialGroup()
                        .addComponent(btprint, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(tampiltransaksikendLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(lbkode, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(tampiltransaksikendLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(1494, Short.MAX_VALUE))
        );

        pnmain.add(tampiltransaksikend, "card2");

        add(pnmain, "card2");
    }// </editor-fold>//GEN-END:initComponents

    private void bttambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttambahActionPerformed
        // TODO add your handling code here:
        if(bttambah.getText().equals("Edit"))
        {
        pnmain.removeAll();
        pnmain.repaint();
        pnmain.revalidate();
        pnmain.add(updatetransaksikend);
        txtkode.setEnabled(false);
       
        controller_kendaraann.isiField(tbdata.getSelectedRow());
        }
        
        else{
        pnmain.removeAll();
        pnmain.repaint();
        pnmain.revalidate();
        pnmain.add(tambahtransaksikend);
        txtkode1.setText(implemet_kendaraann.nomor());
        }
     
        
        
    }//GEN-LAST:event_bttambahActionPerformed

    private void btbatal1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btbatal1ActionPerformed
        // TODO add your handling code here:
        tampilPanel();
        controller_kendaraann.reset();
    }//GEN-LAST:event_btbatal1ActionPerformed

    private void bthapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bthapusActionPerformed
        // TODO add your handling code here:
        controller_kendaraann.delete();
        controller_kendaraann.isiTable();
        controller_kendaraann.reset();;
    }//GEN-LAST:event_bthapusActionPerformed

    private void bttambah1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttambah1ActionPerformed
        // TODO add your handling code here:
        
            controller_kendaraann.update();
            controller_kendaraann.isiTable();
            resetForm();
            tampilPanel();
        
        
    }//GEN-LAST:event_bttambah1ActionPerformed

    private void tbdataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbdataMouseClicked
        // TODO add your handling code here:
        
        if(bttambah.getText().equals("Tambah")){
            bttambah.setText("Edit");
        }
        bthapus.setVisible(true);
        btbatal.setVisible(true);
        bttampil.setVisible(true);
        controller_kendaraann.isiField(tbdata.getSelectedRow());
    }//GEN-LAST:event_tbdataMouseClicked

    private void btbatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btbatalActionPerformed
        // TODO add your handling code here:
        tampilPanel();
        controller_kendaraann.reset();
    }//GEN-LAST:event_btbatalActionPerformed

    private void txtkodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtkodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtkodeActionPerformed

    private void txtcariMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtcariMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtcariMouseClicked

    private void txtcariKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcariKeyTyped
        // TODO add your handling code here:
        
       
    }//GEN-LAST:event_txtcariKeyTyped

    private void cbjenisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbjenisActionPerformed
        // TODO add your handling code here:
        String selectedValue = cbjenis.getSelectedItem().toString();
       if(selectedValue == "Beat"){
           txtharga.setText("18000000");
           txtmerk.setText("Honda");
           Integer harga = Integer.parseInt(txtharga.getText());
           Integer pajak = harga * 10/100;
           Integer total = harga + pajak;
           txtharga.setText(String.valueOf(harga));
           txtpajak.setText(String.valueOf(pajak));
           txttotal.setText(String.valueOf(total));
       }
       else if(selectedValue == "Vario 125"){
           txtharga.setText("22500000");
           txtmerk.setText("Honda");
           Integer harga = Integer.parseInt(txtharga.getText());
           Integer pajak = harga * 10/100;
           Integer total = harga + pajak;
           txtharga.setText(String.valueOf(harga));
           txtpajak.setText(String.valueOf(pajak));
           txttotal.setText(String.valueOf(total));
       }
        else if(selectedValue == "Vario 150"){
           txtharga.setText("25500000");
           txtmerk.setText("Honda");
           Integer harga = Integer.parseInt(txtharga.getText());
           Integer pajak = harga * 10/100;
           Integer total = harga + pajak;
           txtharga.setText(String.valueOf(harga));
           txtpajak.setText(String.valueOf(pajak));
           txttotal.setText(String.valueOf(total));
       }
        else if(selectedValue == "PCX"){
           txtharga.setText("40500000");
           txtmerk.setText("Honda");
           Integer harga = Integer.parseInt(txtharga.getText());
           Integer pajak = harga * 10/100;
           Integer total = harga + pajak;
           txtharga.setText(String.valueOf(harga));
           txtpajak.setText(String.valueOf(pajak));
           txttotal.setText(String.valueOf(total));
       }
        else if(selectedValue == "CBR 150R"){
           txtharga.setText("3728000");
           txtmerk.setText("Honda");
           Integer harga = Integer.parseInt(txtharga.getText());
           Integer pajak = harga * 10/100;
           Integer total = harga + pajak;
           txtharga.setText(String.valueOf(harga));
           txtpajak.setText(String.valueOf(pajak));
           txttotal.setText(String.valueOf(total));
       }
        else if(selectedValue == "CBR 250RR"){
           txtharga.setText("63460000");
           txtmerk.setText("Honda");
           Integer harga = Integer.parseInt(txtharga.getText());
           Integer pajak = harga * 10/100;
           Integer total = harga + pajak;
           txtharga.setText(String.valueOf(harga));
           txtpajak.setText(String.valueOf(pajak));
           txttotal.setText(String.valueOf(total));
       }
        else if(selectedValue == "CB 150R"){
           txtharga.setText("30660000");
           txtmerk.setText("Honda");
           Integer harga = Integer.parseInt(txtharga.getText());
           Integer pajak = harga * 10/100;
           Integer total = harga + pajak;
           txtharga.setText(String.valueOf(harga));
           txtpajak.setText(String.valueOf(pajak));
           txttotal.setText(String.valueOf(total));
       }
        else if(selectedValue == "R15"){
           txtharga.setText("39875000");
           txtmerk.setText("Yamaha");
           Integer harga = Integer.parseInt(txtharga.getText());
           Integer pajak = harga * 10/100;
           Integer total = harga + pajak;
           txtharga.setText(String.valueOf(harga));
           txtpajak.setText(String.valueOf(pajak));
           txttotal.setText(String.valueOf(total));
       }
        else if(selectedValue == "R25"){
           txtharga.setText("63450000");
           txtmerk.setText("Yamaha");
           Integer harga = Integer.parseInt(txtharga.getText());
           Integer pajak = harga * 10/100;
           Integer total = harga + pajak;
           txtharga.setText(String.valueOf(harga));
           txtpajak.setText(String.valueOf(pajak));
           txttotal.setText(String.valueOf(total));
       }
        else if(selectedValue == "AEROX 155"){
           txtharga.setText("27425000");
           txtmerk.setText("Yamaha");
           Integer harga = Integer.parseInt(txtharga.getText());
           Integer pajak = harga * 10/100;
           Integer total = harga + pajak;
           txtharga.setText(String.valueOf(harga));
           txtpajak.setText(String.valueOf(pajak));
           txttotal.setText(String.valueOf(total));
       }
        else if(selectedValue == "LEXi 125"){
           txtharga.setText("23000000");
           txtmerk.setText("Yamaha");
           Integer harga = Integer.parseInt(txtharga.getText());
           Integer pajak = harga * 10/100;
           Integer total = harga + pajak;
           txtharga.setText(String.valueOf(harga));
           txtpajak.setText(String.valueOf(pajak));
           txttotal.setText(String.valueOf(total));
       }
        else if(selectedValue == "Mio M3 125"){
           txtharga.setText("17405000");
           txtmerk.setText("Yamaha");
           Integer harga = Integer.parseInt(txtharga.getText());
           Integer pajak = harga * 10/100;
           Integer total = harga + pajak;
           txtharga.setText(String.valueOf(harga));
           txtpajak.setText(String.valueOf(pajak));
           txttotal.setText(String.valueOf(total));
       }
        else if(selectedValue == "NMAX 155"){
           txtharga.setText("31615000");
           txtmerk.setText("Yamaha");
           Integer harga = Integer.parseInt(txtharga.getText());
           Integer pajak = harga * 10/100;
           Integer total = harga + pajak;
           txtharga.setText(String.valueOf(harga));
           txtpajak.setText(String.valueOf(pajak));
           txttotal.setText(String.valueOf(total));
       }
        else if(selectedValue == "Vixion 155"){
           txtharga.setText("29275000");
           txtmerk.setText("Yamaha");
           Integer harga = Integer.parseInt(txtharga.getText());
           Integer pajak = harga * 10/100;
           Integer total = harga + pajak;
           txtharga.setText(String.valueOf(harga));
           txtpajak.setText(String.valueOf(pajak));
           txttotal.setText(String.valueOf(total));
       }
    }//GEN-LAST:event_cbjenisActionPerformed

    private void btbatal2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btbatal2ActionPerformed
        // TODO add your handling code here:
        tampilPanel();
        controller_kendaraann.reset();
    }//GEN-LAST:event_btbatal2ActionPerformed

    private void txtkode1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtkode1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtkode1ActionPerformed

    private void cbjenis1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbjenis1ActionPerformed
        // TODO add your handling code here:
        String selectedValue = cbjenis1.getSelectedItem().toString();
       if(selectedValue == "Beat"){
           txtharga1.setText("18000000");
           txtmerk1.setText("Honda");
           Integer harga = Integer.parseInt(txtharga1.getText());
           Integer pajak = harga * 10/100;
           Integer total = harga + pajak;
           txtharga1.setText(String.valueOf(harga));
           txtpajak1.setText(String.valueOf(pajak));
           txttotal1.setText(String.valueOf(total));
       }
       else if(selectedValue == "Vario 125"){
           txtharga1.setText("22500000");
           txtmerk1.setText("Honda");
           Integer harga = Integer.parseInt(txtharga1.getText());
           Integer pajak = harga * 10/100;
           Integer total = harga + pajak;
           txtharga1.setText(String.valueOf(harga));
           txtpajak1.setText(String.valueOf(pajak));
           txttotal1.setText(String.valueOf(total));
       }
        else if(selectedValue == "Vario 150"){
           txtharga1.setText("25500000");
           txtmerk1.setText("Honda");
           Integer harga = Integer.parseInt(txtharga1.getText());
           Integer pajak = harga * 10/100;
           Integer total = harga + pajak;
           txtharga1.setText(String.valueOf(harga));
           txtpajak1.setText(String.valueOf(pajak));
           txttotal1.setText(String.valueOf(total));
       }
        else if(selectedValue == "PCX"){
           txtharga1.setText("40500000");
           txtmerk1.setText("Honda");
           Integer harga = Integer.parseInt(txtharga1.getText());
           Integer pajak = harga * 10/100;
           Integer total = harga + pajak;
           txtharga1.setText(String.valueOf(harga));
           txtpajak1.setText(String.valueOf(pajak));
           txttotal1.setText(String.valueOf(total));
       }
        else if(selectedValue == "CBR 150R"){
           txtharga1.setText("3728000");
           txtmerk1.setText("Honda");
           Integer harga = Integer.parseInt(txtharga1.getText());
           Integer pajak = harga * 10/100;
           Integer total = harga + pajak;
           txtharga1.setText(String.valueOf(harga));
           txtpajak1.setText(String.valueOf(pajak));
           txttotal1.setText(String.valueOf(total));
       }
        else if(selectedValue == "CBR 250RR"){
           txtharga1.setText("63460000");
           txtmerk1.setText("Honda");
           Integer harga = Integer.parseInt(txtharga1.getText());
           Integer pajak = harga * 10/100;
           Integer total = harga + pajak;
           txtharga1.setText(String.valueOf(harga));
           txtpajak1.setText(String.valueOf(pajak));
           txttotal1.setText(String.valueOf(total));
       }
        else if(selectedValue == "CB 150R"){
           txtharga1.setText("30660000");
           txtmerk1.setText("Honda");
           Integer harga = Integer.parseInt(txtharga1.getText());
           Integer pajak = harga * 10/100;
           Integer total = harga + pajak;
           txtharga1.setText(String.valueOf(harga));
           txtpajak1.setText(String.valueOf(pajak));
           txttotal1.setText(String.valueOf(total));
       }
        else if(selectedValue == "R15"){
           txtharga1.setText("39875000");
           txtmerk1.setText("Yamaha");
           Integer harga = Integer.parseInt(txtharga1.getText());
           Integer pajak = harga * 10/100;
           Integer total = harga + pajak;
           txtharga1.setText(String.valueOf(harga));
           txtpajak1.setText(String.valueOf(pajak));
           txttotal1.setText(String.valueOf(total));
       }
        else if(selectedValue == "R25"){
           txtharga1.setText("63450000");
           txtmerk1.setText("Yamaha");
           Integer harga = Integer.parseInt(txtharga1.getText());
           Integer pajak = harga * 10/100;
           Integer total = harga + pajak;
           txtharga1.setText(String.valueOf(harga));
           txtpajak1.setText(String.valueOf(pajak));
           txttotal1.setText(String.valueOf(total));
       }
        else if(selectedValue == "AEROX 155"){
           txtharga1.setText("27425000");
           txtmerk1.setText("Yamaha");
           Integer harga = Integer.parseInt(txtharga1.getText());
           Integer pajak = harga * 10/100;
           Integer total = harga + pajak;
           txtharga1.setText(String.valueOf(harga));
           txtpajak1.setText(String.valueOf(pajak));
           txttotal1.setText(String.valueOf(total));
       }
        else if(selectedValue == "LEXi 125"){
           txtharga1.setText("23000000");
           txtmerk1.setText("Yamaha");
           Integer harga = Integer.parseInt(txtharga1.getText());
           Integer pajak = harga * 10/100;
           Integer total = harga + pajak;
           txtharga1.setText(String.valueOf(harga));
           txtpajak1.setText(String.valueOf(pajak));
           txttotal1.setText(String.valueOf(total));
       }
        else if(selectedValue == "Mio M3 125"){
           txtharga1.setText("17405000");
           txtmerk1.setText("Yamaha");
           Integer harga = Integer.parseInt(txtharga1.getText());
           Integer pajak = harga * 10/100;
           Integer total = harga + pajak;
           txtharga1.setText(String.valueOf(harga));
           txtpajak1.setText(String.valueOf(pajak));
           txttotal1.setText(String.valueOf(total));
       }
        else if(selectedValue == "NMAX 155"){
           txtharga1.setText("31615000");
           txtmerk1.setText("Yamaha");
           Integer harga = Integer.parseInt(txtharga1.getText());
           Integer pajak = harga * 10/100;
           Integer total = harga + pajak;
           txtharga1.setText(String.valueOf(harga));
           txtpajak1.setText(String.valueOf(pajak));
           txttotal1.setText(String.valueOf(total));
       }
        else if(selectedValue == "Vixion 155"){
           txtharga1.setText("29275000");
           txtmerk1.setText("Yamaha");
           Integer harga = Integer.parseInt(txtharga1.getText());
           Integer pajak = harga * 10/100;
           Integer total = harga + pajak;
           txtharga1.setText(String.valueOf(harga));
           txtpajak1.setText(String.valueOf(pajak));
           txttotal1.setText(String.valueOf(total));
       }
    }//GEN-LAST:event_cbjenis1ActionPerformed

    private void btcariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btcariActionPerformed
        // TODO add your handling code here:
        controller_kendaraann.carinama();
        
    }//GEN-LAST:event_btcariActionPerformed

    private void bttambah2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttambah2ActionPerformed
        // TODO add your handling code here:
       controller_kendaraann.insert();
        controller_kendaraann.isiTable();
        resetForm();
        tampilPanel();
    }//GEN-LAST:event_bttambah2ActionPerformed

    private void bttampilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttampilActionPerformed
        // TODO add your handling code here:
        pnmain.removeAll();
        pnmain.repaint();
        pnmain.revalidate();
        pnmain.add(tampiltransaksikend);
        
       
        controller_kendaraann.isiLabel(tbdata.getSelectedRow());
    }//GEN-LAST:event_bttampilActionPerformed

    private void btbatal4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btbatal4ActionPerformed
        // TODO add your handling code here:
        tampilPanel();
        controller_kendaraann.reset();
    }//GEN-LAST:event_btbatal4ActionPerformed

    private void btprintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btprintActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btprintActionPerformed

    private void btedit5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btedit5ActionPerformed
        // TODO add your handling code here:
        pnmain.removeAll();
        pnmain.repaint();
        pnmain.revalidate();
        pnmain.add(updatetransaksikend);
        txtkode.setEnabled(false);
       
        controller_kendaraann.isiField(tbdata.getSelectedRow());
    }//GEN-LAST:event_btedit5ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btbatal;
    private javax.swing.JButton btbatal1;
    private javax.swing.JButton btbatal2;
    private javax.swing.JButton btbatal4;
    private javax.swing.JButton btcari;
    private javax.swing.JButton btedit5;
    private javax.swing.JButton bthapus;
    private javax.swing.JButton btprint;
    private javax.swing.JButton bttambah;
    private javax.swing.JButton bttambah1;
    private javax.swing.JButton bttambah2;
    private javax.swing.JButton bttampil;
    private javax.swing.JComboBox<String> cbjenis;
    private javax.swing.JComboBox<String> cbjenis1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JLabel lbalamat;
    private javax.swing.JLabel lbharga;
    private javax.swing.JLabel lbjenis;
    private javax.swing.JLabel lbkode;
    private javax.swing.JLabel lbmerk;
    private javax.swing.JLabel lbnama;
    private javax.swing.JLabel lbnotelp;
    private javax.swing.JLabel lbpajak;
    private javax.swing.JLabel lbtotal;
    private javax.swing.JPanel pndatatransaksikend;
    private javax.swing.JPanel pnmain;
    private javax.swing.JPanel tambahtransaksikend;
    private javax.swing.JPanel tampiltransaksikend;
    private javax.swing.JTable tbdata;
    private javax.swing.JTextField txtalamat;
    private javax.swing.JTextField txtcari;
    private javax.swing.JTextField txtharga;
    private javax.swing.JTextField txtharga1;
    private javax.swing.JTextField txtkode;
    private javax.swing.JTextField txtkode1;
    private javax.swing.JTextField txtmerk;
    private javax.swing.JTextField txtmerk1;
    private javax.swing.JTextField txtnalamat1;
    private javax.swing.JTextField txtnama;
    private javax.swing.JTextField txtnama1;
    private javax.swing.JTextField txtpajak;
    private javax.swing.JTextField txtpajak1;
    private javax.swing.JTextField txttelepon;
    private javax.swing.JTextField txttelepon1;
    private javax.swing.JTextField txttotal;
    private javax.swing.JTextField txttotal1;
    private javax.swing.JPanel updatetransaksikend;
    // End of variables declaration//GEN-END:variables

private void aktif(){
    txtkode.setEnabled(true);
    txtnama.setEnabled(true);
    
}    

    public JTextField getTxtalamat() {
        return txtalamat;
    }

    public void setTxtalamat(JTextField txtalamat) {
        this.txtalamat = txtalamat;
    }

    public JTextField getTxttelepon() {
        return txttelepon;
    }

    public void setTxttelepon(JTextField txttelepon) {
        this.txttelepon = txttelepon;
    }



    public JTextField getTxtnalamat1() {
        return txtnalamat1;
    }

    public void setTxtnalamat1(JTextField txtnalamat1) {
        this.txtnalamat1 = txtnalamat1;
    }

    public JTextField getTxttelepon1() {
        return txttelepon1;
    }

    public void setTxttelepon1(JTextField txttelepon1) {
        this.txttelepon1 = txttelepon1;
    }



    public JButton getBtbatal2() {
        return btbatal2;
    }

    public void setBtbatal2(JButton btbatal2) {
        this.btbatal2 = btbatal2;
    }

    public JButton getBttambah2() {
        return bttambah2;
    }

    public void setBttambah2(JButton bttambah2) {
        this.bttambah2 = bttambah2;
    }

    public JComboBox<String> getCbjenis1() {
        return cbjenis1;
    }

    public void setCbjenis1(JComboBox<String> cbjenis1) {
        this.cbjenis1 = cbjenis1;
    }

    public JTextField getTxtharga1() {
        return txtharga1;
    }

    public void setTxtharga1(JTextField txtharga1) {
        this.txtharga1 = txtharga1;
    }

    public JTextField getTxtkode1() {
        return txtkode1;
    }

    public void setTxtkode1(JTextField txtkode1) {
        this.txtkode1 = txtkode1;
    }

    public JTextField getTxtmerk1() {
        return txtmerk1;
    }

    public void setTxtmerk1(JTextField txtmerk1) {
        this.txtmerk1 = txtmerk1;
    }

    public JTextField getTxtnama1() {
        return txtnama1;
    }

    public void setTxtnama1(JTextField txtnama1) {
        this.txtnama1 = txtnama1;
    }

    public JTextField getTxtpajak1() {
        return txtpajak1;
    }

    public void setTxtpajak1(JTextField txtpajak1) {
        this.txtpajak1 = txtpajak1;
    }

    public JTextField getTxttotal1() {
        return txttotal1;
    }

    public void setTxttotal1(JTextField txttotal1) {
        this.txttotal1 = txttotal1;
    }
 

private void resetForm(){
    bttambah.requestFocus();
    bttambah.setText("Tambah");
    txtkode.setText("");
    txtnama.setText("");

}

private void tampilPanel(){
    pnmain.removeAll();
    pnmain.add(new View_Kendaraann());
    pnmain.repaint();
    pnmain.revalidate();
}

    public JButton getBtbatal() {
        return btbatal;
    }

    public void setBtbatal(JButton btbatal) {
        this.btbatal = btbatal;
    }

    public JButton getBtbatal1() {
        return btbatal1;
    }

    public void setBtbatal1(JButton btbatal1) {
        this.btbatal1 = btbatal1;
    }

    public JButton getBthapus() {
        return bthapus;
    }

    public void setBthapus(JButton bthapus) {
        this.bthapus = bthapus;
    }

    public JButton getBttambah() {
        return bttambah;
    }

    public void setBttambah(JButton bttambah) {
        this.bttambah = bttambah;
    }

    public JButton getBttambah1() {
        return bttambah1;
    }

    public void setBttambah1(JButton bttambah1) {
        this.bttambah1 = bttambah1;
    }

    public JComboBox<String> getCbjenis() {
        return cbjenis;
    }

    public void setCbjenis(JComboBox<String> cbjenis) {
        this.cbjenis = cbjenis;
    }

    public JTable getTbdata() {
        return tbdata;
    }

    public void setTbdata(JTable tbdata) {
        this.tbdata = tbdata;
    }

    public JTextField getTxtcari() {
        return txtcari;
    }

    public void setTxtcari(JTextField txtcari) {
        this.txtcari = txtcari;
    }

    public JTextField getTxtharga() {
        return txtharga;
    }

    public void setTxtharga(JTextField txtharga) {
        this.txtharga = txtharga;
    }

    public JTextField getTxtkode() {
        return txtkode;
    }

    public void setTxtkode(JTextField txtkode) {
        this.txtkode = txtkode;
    }

    public JTextField getTxtmerk() {
        return txtmerk;
    }

    public void setTxtmerk(JTextField txtmerk) {
        this.txtmerk = txtmerk;
    }

    public JTextField getTxtnama() {
        return txtnama;
    }

    public void setTxtnama(JTextField txtnama) {
        this.txtnama = txtnama;
    }

    public JTextField getTxtpajak() {
        return txtpajak;
    }

    public void setTxtpajak(JTextField txtpajak) {
        this.txtpajak = txtpajak;
    }

    public JTextField getTxttotal() {
        return txttotal;
    }

    public void setTxttotal(JTextField txttotal) {
        this.txttotal = txttotal;
    }

    public JLabel getLbalamat() {
        return lbalamat;
    }

    public void setLbalamat(JLabel lbalamat) {
        this.lbalamat = lbalamat;
    }

    public JLabel getLbharga() {
        return lbharga;
    }

    public void setLbharga(JLabel lbharga) {
        this.lbharga = lbharga;
    }

    public JLabel getLbjenis() {
        return lbjenis;
    }

    public void setLbjenis(JLabel lbjenis) {
        this.lbjenis = lbjenis;
    }

    public JLabel getLbkode() {
        return lbkode;
    }

    public void setLbkode(JLabel lbkode) {
        this.lbkode = lbkode;
    }

    public JLabel getLbmerk() {
        return lbmerk;
    }

    public void setLbmerk(JLabel lbmerk) {
        this.lbmerk = lbmerk;
    }

    public JLabel getLbnama() {
        return lbnama;
    }

    public void setLbnama(JLabel lbnama) {
        this.lbnama = lbnama;
    }

    public JLabel getLbnotelp() {
        return lbnotelp;
    }

    public void setLbnotelp(JLabel lbnotelp) {
        this.lbnotelp = lbnotelp;
    }

    public JLabel getLbpajak() {
        return lbpajak;
    }

    public void setLbpajak(JLabel lbpajak) {
        this.lbpajak = lbpajak;
    }

    public JLabel getLbtotal() {
        return lbtotal;
    }

    public void setLbtotal(JLabel lbtotal) {
        this.lbtotal = lbtotal;
    }

    


}

        

