/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package kompormoto.View;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import javax.swing.ImageIcon;


import javax.swing.JFrame;

/**
 *
 * @author ASUS
 */
public class View_Dashboard extends javax.swing.JFrame {

    /**
     * Creates new form View_Dashboard
     */
    public View_Dashboard(String Id, String Nama, String Jabatan) {
        initComponents();
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        
        execute();
    }

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnnavbar = new javax.swing.JPanel();
        pnsidebar = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        pnmenu = new javax.swing.JPanel();
        pncontent = new javax.swing.JPanel();
        pnutama = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        pnnavbar.setBackground(new java.awt.Color(6, 114, 202));
        pnnavbar.setPreferredSize(new java.awt.Dimension(876, 70));

        javax.swing.GroupLayout pnnavbarLayout = new javax.swing.GroupLayout(pnnavbar);
        pnnavbar.setLayout(pnnavbarLayout);
        pnnavbarLayout.setHorizontalGroup(
            pnnavbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 963, Short.MAX_VALUE)
        );
        pnnavbarLayout.setVerticalGroup(
            pnnavbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );

        getContentPane().add(pnnavbar, java.awt.BorderLayout.PAGE_START);

        pnsidebar.setBackground(new java.awt.Color(255, 255, 255));
        pnsidebar.setPreferredSize(new java.awt.Dimension(300, 479));

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));

        pnmenu.setBackground(new java.awt.Color(255, 255, 255));
        pnmenu.setLayout(new javax.swing.BoxLayout(pnmenu, javax.swing.BoxLayout.Y_AXIS));
        jScrollPane1.setViewportView(pnmenu);

        javax.swing.GroupLayout pnsidebarLayout = new javax.swing.GroupLayout(pnsidebar);
        pnsidebar.setLayout(pnsidebarLayout);
        pnsidebarLayout.setHorizontalGroup(
            pnsidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );
        pnsidebarLayout.setVerticalGroup(
            pnsidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 559, Short.MAX_VALUE)
        );

        getContentPane().add(pnsidebar, java.awt.BorderLayout.LINE_START);

        pncontent.setBackground(new java.awt.Color(255, 255, 255));

        pnutama.setBackground(new java.awt.Color(255, 255, 255));
        pnutama.setMaximumSize(new java.awt.Dimension(2147483647, 2000));
        pnutama.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout pncontentLayout = new javax.swing.GroupLayout(pncontent);
        pncontent.setLayout(pncontentLayout);
        pncontentLayout.setHorizontalGroup(
            pncontentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnutama, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pncontentLayout.setVerticalGroup(
            pncontentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnutama, javax.swing.GroupLayout.DEFAULT_SIZE, 559, Short.MAX_VALUE)
        );

        getContentPane().add(pncontent, java.awt.BorderLayout.CENTER);

        setSize(new java.awt.Dimension(977, 666));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        pnutama.add(new View_Home());
        pnutama.repaint();
        pnutama.revalidate();
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(View_Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(View_Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(View_Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(View_Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new View_Dashboard("Id", "Nama", "Jabatan").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel pncontent;
    private javax.swing.JPanel pnmenu;
    private javax.swing.JPanel pnnavbar;
    private javax.swing.JPanel pnsidebar;
    private javax.swing.JPanel pnutama;
    // End of variables declaration//GEN-END:variables

    private void execute() {
        ImageIcon iconMaster = new ImageIcon("src/img/icons8_forward_24px.png");
        ImageIcon iconKendaraan = new ImageIcon("src/img/select_20px.png");
        
        View_Item adKendaraan1 = new View_Item(null, true, iconKendaraan, "Penjualan Kendaraan", new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent arg0) {
                pnutama.removeAll();
                pnutama.add(new View_Kendaraann());
                pnutama.repaint();
                pnutama.revalidate();
            }
        });
        
       
        
        
        View_Item menuHome = new View_Item(iconMaster, false, null, "Home", new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent arg0) {
                pnutama.removeAll();
                pnutama.add(new View_Home());
                pnutama.repaint();
                pnutama.revalidate();
            }
        });
        View_Item menuAdmin = new View_Item(iconMaster, false, null, "Admin", null,adKendaraan1);
        View_Item menuReport = new View_Item(iconMaster, false, null, "Report", null);
        
        addMenu(menuHome,menuAdmin,menuReport);
    }
    
    private void addMenu(View_Item...menu){
        for (int i = 0; i<menu.length; i++){
            pnmenu.add(menu[i]);
            ArrayList<View_Item> subMenu = menu[i].getSubMenu();
            for (View_Item m : subMenu){
                addMenu(m);
            }
        }
        pnmenu.revalidate();
    }
    
    
}
